deployment template:
kind: Deployment
apiVersion: apps/v1
metadata:
  name: romank8s
  namespace: romank8s
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: romank8s
  template:
    metadata:
      labels:
        app: romank8s
    spec:
      containers:
      - name: romank8s
        image: devops.azurecr.io/romanm:test5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: romank8s-service
  namespace: romank8s
spec:
  selector:
    app: romank8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer