apiVersion: v1
kind: Service
metadata:
  name: romank8s-service
  namespace: romank8s
spec:
  selector:
    app: romank8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer